datasets:
  train: {HR_size: 128, batch_size: 16, dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub.lmdb,
    dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub_bicLRx4.lmdb,
    mode: LRHR, n_workers: 8, name: DIV2K, subset_file: null, use_flip: true, use_rot: true,
    use_shuffle: true}
  val: {dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/val_set5/Set5, dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/val_set5/Set5_bicLRx4,
    mode: LRHR, name: val_set5}
gpu_ids: [0]
logger: {print_freq: 200, save_checkpoint_freq: 5000.0}
model: sr
name: debug_001_RRDB_PSNR_x4_DIV2K
network_G: {gc: 32, group: 1, in_nc: 3, mode: CNA, nb: 23, nf: 64, norm_type: null,
  out_nc: 3, which_model_G: RRDB_net}
path: {pretrain_model_G: null, root: /home/xtwang/Projects/BasicSR}
scale: 4
train:
  lr_G: 0.0002
  lr_gamma: 0.5
  lr_scheme: MultiStepLR
  lr_steps: [200000, 400000, 600000, 800000]
  manual_seed: 0
  niter: 1000000.0
  pixel_criterion: l1
  pixel_weight: 1.0
  val_freq: 5000.0
use_tb_logger: true
