datasets:
  train: {HR_size: 128, batch_size: 16, dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub.lmdb,
    dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub_bicLRx4.lmdb,
    mode: LRHR, n_workers: 8, name: DIV2K, subset_file: null, use_flip: true, use_rot: true,
    use_shuffle: true}
  val: {dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/val_set14_part/Set14, dataroot_LR: /mnt/SSD/xtwang/BasicSR_datasets/val_set14_part/Set14_bicLRx4,
    mode: LRHR, name: val_set14_part}
gpu_ids: [0]
logger: {print_freq: 200, save_checkpoint_freq: 5000.0}
model: srgan
name: debug_002_SRGAN_x4_DIV2K
network_D: {act_type: leakyrelu, in_nc: 3, mode: CNA, nf: 64, norm_type: batch, which_model_D: discriminator_vgg_128}
network_G: {in_nc: 3, mode: CNA, nb: 16, nf: 64, norm_type: null, out_nc: 3, which_model_G: sr_resnet}
path: {pretrain_model_G: ../experiments/pretrained_models/SRResNet_bicx4_in3nf64nb16.pth,
  root: /home/xtwang/Projects/BasicSR}
scale: 4
train:
  beta1_D: 0.9
  beta1_G: 0.9
  feature_criterion: l1
  feature_weight: 1
  gan_type: vanilla
  gan_weight: 0.005
  lr_D: 0.0001
  lr_G: 0.0001
  lr_gamma: 0.5
  lr_scheme: MultiStepLR
  lr_steps: [50000, 100000, 200000, 300000]
  manual_seed: 0
  niter: 500000.0
  pixel_criterion: l1
  pixel_weight: 0.01
  val_freq: 5000.0
  weight_decay_D: 0
  weight_decay_G: 0
use_tb_logger: true
