datasets:
    generate: {lr_dir: /home/super/images/images, hr_dir: /home/super/images/images ,name: asc}
GPUs: [0,1,2,3]
model: ESRGAN
name: RRDB_ESRGAN_Flickr2K
GAN: {path: /home/super/models/RRDB_PSNR_x4.pth}
Discriminator: {}
result_dir: ./results
