datasets:
        generate: {dataroot_LR: /home/super/images/images, dataroot_HR: /home/super/images/images ,name: asc}
gpu_ids: [2,3]
model: srragan
name: RRDB_ESRGAN_x4
network_G: {gc: 32, group: 1, in_nc: 3, mode: CNA, nb: 23, nf: 64, norm_type: null,
  out_nc: 3}
network_D: {act_type: leakyrelu, in_nc: 3, mode: CNA, nf: 64, norm_type: batch}
path: {results_root: ../results, root: /home/super/Coding/BasicSR}
scale: 4
suffix: _ESRGAN
