datasets:
  train: {hr_sz: 128, minibatch: 32, hr_dir: /home/super/Flickr2K/Flickr2K_HR_sub.lmdb,
    lr_dir: /home/super/Flickr2K/Flickr2K_HR_sub_bicLRx4.lmdb, n_workers: 16,
    name: DIV2K}
  val: {hr_dir: /home/super/DIV2K/DIV2K_valid_HR, lr_dir: /home/super/DIV2K/DIV2K_valid_bicLRx4,
    name: val_div2k_part}
GPUs: [0,1]
model: srragan
name: 2g_RRDB_ESRGAN_DIV2K
Discriminator: {act_type: leakyrelu, in_nc: 3, mode: CNA, nf: 64, norm_type: batch}
GAN: {path: /home/super/models/RRDB_PSNR_x4.pth ,gc: 32, group: 1, in_nc: 3, mode: CNA, nb: 23, nf: 64, norm_type: null,
  out_nc: 3}
beta1_D: 0.9
beta1_G: 0.9
feature_criterion: l1
feature_weight: 1
gan_weight: 0.005
lr_D: 0.0001
lr_G: 0.0001
lr_gamma: 0.5
lr_steps: [50000, 100000, 200000, 300000]
manual_seed: 0
pixel_criterion: l1
pixel_weight: 0.01
val_freq: 5000.0
weight_decay_D: 0
weight_decay_G: 0
total_iters: 15000.0
enable_tensorboard: true
